### ISSUE TITLE
cannot compile in gulp

### ISSUE THREAD

**Issue by schel4ok** [niksmr/vue-masked-input#4]
I downloaded your package in my laravel 5.3 + vuejs 2.1.3
` npm install vue-masked-input --save `

then in app.js
`import MaskedInput from 'vue-masked-input';`

then in vue component I have field (I also have vee-validate)
```
<div class="form-group col-xs-12 col-sm-6" :class="{'has-error': errors.has('phone') }">
         <label>phone</label>
         <div class="input-group">
                 <span class="input-group-addon"><i class="fa fa-phone"></i></span>
                 <masked-input v-model="phone" mask="\+\7 (111) 111-11-11" placeholder="phone" name="phone"/>
         </div>
         <p class="text-danger" v-if="errors.has('phone')">{{ errors.first('phone') }}</p>
</div>
```

then I have errors when trying to compile all this in gulp.

```
> gulp
[19:50:45] Using gulpfile d:\OpenServer\domains\mysite.new\gulpfile.js
[19:50:45] Starting 'all'...
[19:50:45] Starting 'copy'...
[19:50:45] Finished 'copy' after 55 ms
[19:50:45] Starting 'copy'...
[19:50:45] Finished 'copy' after 9.93 ms
[19:50:45] Starting 'sass'...
[19:50:46] Finished 'sass' after 883 ms
[19:50:46] Starting 'styles'...
[19:50:46] Finished 'styles' after 52 ms
[19:50:46] Starting 'webpack'...
{ [Error: ./~/buble-loader!./~/vue-loader/lib/selector.js?type=script&index=0!./~/vue-masked-input/src/MaskedInput.vue
Module build failed: Error
    at ForOfStatement.initialise (d:\OpenServer\domains\mysite.new\node_modules\buble\dist\buble.umd.js:2004:65)
    at d:\OpenServer\domains\mysite.new\node_modules\buble\dist\buble.umd.js:9381:56
    at Array.forEach (native)
    at BlockStatement.initialise (d:\OpenServer\domains\mysite.new\node_modules\buble\dist\buble.umd.js:9381:15)
    at Node.initialise (d:\OpenServer\domains\mysite.new\node_modules\buble\dist\buble.umd.js:858:12)
    at d:\OpenServer\domains\mysite.new\node_modules\buble\dist\buble.umd.js:9381:56
    at Array.forEach (native)
    at BlockStatement.initialise (d:\OpenServer\domains\mysite.new\node_modules\buble\dist\buble.umd.js:9381:15)
    at FunctionExpression.initialise (d:\OpenServer\domains\mysite.new\node_modules\buble\dist\buble.umd.js:858:12)
 @ ./~/vue-masked-input/src/MaskedInput.vue 5:18-105
 @ ./resources/assets/js/frontend/app.js]
  message: './~/buble-loader!./~/vue-loader/lib/selector.js?type=script&index=0!./~/vue-masked-input/src/MaskedInput.vue\nModule build fai
led: Error\n    at ForOfStatement.initialise (d:\\OpenServer\\domains\\mysite.new\\node_modules\\buble\\dist\\buble.umd.js:2004:65)\n    a
t d:\\OpenServer\\domains\\mysite.new\\node_modules\\buble\\dist\\buble.umd.js:9381:56\n    at Array.forEach (native)\n    at BlockStateme
nt.initialise (d:\\OpenServer\\domains\\mysite.new\\node_modules\\buble\\dist\\buble.umd.js:9381:15)\n    at Node.initialise (d:\\OpenServ
er\\domains\\mysite.new\\node_modules\\buble\\dist\\buble.umd.js:858:12)\n    at d:\\OpenServer\\domains\\mysite.new\\node_modules\\buble\
\dist\\buble.umd.js:9381:56\n    at Array.forEach (native)\n    at BlockStatement.initialise (d:\\OpenServer\\domains\\mysite.new\\node_mo
dules\\buble\\dist\\buble.umd.js:9381:15)\n    at FunctionExpression.initialise (d:\\OpenServer\\domains\\mysite.new\\node_modules\\buble\
\dist\\buble.umd.js:858:12)\n @ ./~/vue-masked-input/src/MaskedInput.vue 5:18-105\n @ ./resources/assets/js/frontend/app.js',
  showStack: false,
  showProperties: true,
  plugin: 'webpack-stream',
  __safety: { toString: [Function: bound ] } }

```

**Comment by etjie** [comment]
I'm having the same issue.

**Comment by laerciokelson** [comment]
Me too

**Comment by niksmr** [comment]
Not sure exactly the cause of this error, but could you update to 0.4.1 and test it again? Maybe you didn't have vue-loader, so in 0.4.1 i'm switched to .js- instead of .vue- component, and if lack of vue-loader was the cause now that's gonna be fixed

**Comment by ikoolik** [comment]
Having the same issue with 0.4.1

**Comment by niksmr** [comment]
In version 0.5.0 the output js no longer contains ES6-features. Is there an error now?

**Comment by etjie** [comment]
Im installing latest version, compile with gulp is working now. thank you.

**Comment by ariefitriadin** [comment]
Thanks Etjie for information , I have the same issue , I ' ll try installing latest version
